/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank.java;

public class App {
    public static void main(String[] args) {
        Teller teller = new Teller();
        teller.start();
    }
}
